### ISSUE TITLE
Failing to find motif PWM models

### ISSUE THREAD

**Issue by vitkl** [aertslab/pycisTopic#34]
Hi 

Thank you for building this fantastic resource. I would like to use your motif PWM models to scan my sequences - either using https://github.com/aertslab/create_cisTarget_databases (cluster-buster format) or using motifmatchr (jaspar/meme/TFBSTools package objects in R) - however, I failed to locate the relevant files containing PWM models mentioned on this page https://pycistarget.readthedocs.io/en/latest/motif_table.html. The documentation seems to suggest that `create_cisTarget_databases` needs cluster-buster format files as input to `create_cistarget_motif_databases.py -M $cbdir` but never shows where to find them.

**Comment by cbravo93** [comment]
Hi @vitkl !

At the moment we provide precomputed databases for human, mouse and fly that you can use to use SCENIC+ at https://resources.aertslab.org/cistarget/ . Since the motif collection is one of the key new features in SCENIC+ we are planning to release the PWM upon publication. However, you can send us an email to carmen.bravogonzalezblas@kuleuven.be, seppe.dewinter@kuleuven.be or stein.aerts@kuleuven.be with your motivation to request the collection and we may be decide to share it privately with you. We will add a warning on this in the create_cistarget_databases repository.

Cheers!

Carmen

**Comment by vitkl** [comment]
Huge congratulations on the publication of Scenic+!

Does this mean that you will now release the motif collection and motif-TF annotations?

**Comment by vitkl** [comment]
Hi @cbravo93 

Huge congratulations on the publication of Scenic+!

Does this mean that you will now release the motif collection and motif-TF annotations?

**Comment by cbravo93** [comment]
Hi @vitkl !

Indeed, you can find them at: https://resources.aertslab.org/cistarget/motif_collections/ (logos, PWMs in cb format (singletons)). Annotations per specie is available at: https://resources.aertslab.org/cistarget/motif2tf/. Note that transfac_pro motif are not included in the singletons folder as we cannot share them because they require a license.

Cheers!

C

**Comment by vitkl** [comment]
Fantastic, thanks for pointing me in the right direction and releasing the models.
